### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jjm0022** [adcirc/gahm#1]
I'm looking to implement the GAHM in matlab to generate wind fields using ATCF data. Just curious if this project has been abandoned? The README says its' still under construction so I'm assuming if it were completed it would be here. 

@zcobell if it hasn't been completed have the most recent changes been pushed to github?

**Comment by zcobell** [comment]
Hi @jjm0022 - the project has not been abandoned, however we had to jump on a few other things over the last bunch of months. We are tentatively planning to have this working this spring, however, what we have currently isn't quite right. Hope to be able to have a release version soon. Thanks for taking a peek and please stay tuned.

**Comment by jjm0022** [comment]
Awesome, thanks for the update. Looking forward to future updates!
